# Generated by Django 3.1.7 on 2021-04-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('followed', 'follower')},
        ),
    ]
